# Загрузка данных

In [ ]:
# from google.colab import userdata
# import json
# import os

# KAGGLE_JSON_PATH = os.path.expanduser("~/.config/kaggle/kaggle.json")

# kaggle_dir = os.path.dirname(KAGGLE_JSON_PATH)
# os.makedirs(kaggle_dir, exist_ok=True)

# kaggle_json = json.loads(userdata.get("kaggle_json"))

# with open(KAGGLE_JSON_PATH, "w") as f:
#     json.dump(kaggle_json, f)

# !chmod 600 ~/.config/kaggle/kaggle.json

# !kaggle competitions download -c critical-temperature-of-superconductors
# !unzip /content/critical-temperature-of-superconductors.zip

Downloading critical-temperature-of-superconductors.zip to /content
  0% 0.00/8.64M [00:00<?, ?B/s]
100% 8.64M/8.64M [00:00<00:00, 492MB/s]
Archive:  /content/critical-temperature-of-superconductors.zip
  inflating: Samsung_Baseline____.ipynb
  inflating: formula_test.csv
  inflating: formula_train.csv
  inflating: test.csv
  inflating: train.csv

# Анализ датасета

Сразу видим очень много признаков. Все признаки численные, пропуски отсутствуют. Из-за кол-ва признаков скорее всего придется снижать размерность пространства признаков

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import RidgeCV, LassoCV

plt.style.use("ggplot")
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 100)

df = pd.read_csv("/content/train.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17010 entries, 0 to 17009
Data columns (total 82 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   number_of_elements               17010 non-null  int64
 1   mean_atomic_mass                 17010 non-null  float64
 2   wtd_mean_atomic_mass             17010 non-null  float64
 3   gmean_atomic_mass                17010 non-null  float64
 4   wtd_gmean_atomic_mass            17010 non-null  float64
 5   entropy_atomic_mass              17010 non-null  float64
 6   wtd_entropy_atomic_mass          17010 non-null  float64
 7   range_atomic_mass                17010 non-null  float64
 8   wtd_range_atomic_mass            17010 non-null  float64
 9   std_atomic_mass                  17010 non-null  float64
 10  wtd_std_atomic_mass              17010 non-null  float64
 11  mean_fie                         17010 non-null  float64
 12  wtd_mean_fie                     17010 non-null  float64
 13  gmean_fie                        17010 non-null  float64
 14  wtd_gmean_fie                    17010 non-null  float64
 15  entropy_fie                      17010 non-null  float64
 16  wtd_entropy_fie                  17010 non-null  float64
 17  range_fie                        17010 non-null  float64
 18  wtd_range_fie                    17010 non-null  float64
 19  std_fie                          17010 non-null  float64
 20  wtd_std_fie                      17010 non-null  float64
 21  mean_atomic_radius               17010 non-null  float64
 22  wtd_mean_atomic_radius           17010 non-null  float64
 23  gmean_atomic_radius              17010 non-null  float64
 24  wtd_gmean_atomic_radius          17010 non-null  float64
 25  entropy_atomic_radius            17010 non-null  float64
 26  wtd_entropy_atomic_radius        17010 non-null  float64
 27  range_atomic_radius              17010 non-null  int64
 28  wtd_range_atomic_radius          17010 non-null  float64
 29  std_atomic_radius                17010 non-null  float64
 30  wtd_std_atomic_radius            17010 non-null  float64
 31  mean_Density                     17010 non-null  float64
 32  wtd_mean_Density                 17010 non-null  float64
 33  gmean_Density                    17010 non-null  float64
 34  wtd_gmean_Density                17010 non-null  float64
 35  entropy_Density                  17010 non-null  float64
 36  wtd_entropy_Density              17010 non-null  float64
 37  range_Density                    17010 non-null  float64
 38  wtd_range_Density                17010 non-null  float64
 39  std_Density                      17010 non-null  float64
 40  wtd_std_Density                  17010 non-null  float64
 41  mean_ElectronAffinity            17010 non-null  float64
 42  wtd_mean_ElectronAffinity        17010 non-null  float64
 43  gmean_ElectronAffinity           17010 non-null  float64
 44  wtd_gmean_ElectronAffinity       17010 non-null  float64
 45  entropy_ElectronAffinity         17010 non-null  float64
 46  wtd_entropy_ElectronAffinity     17010 non-null  float64
 47  range_ElectronAffinity           17010 non-null  float64
 48  wtd_range_ElectronAffinity       17010 non-null  float64
 49  std_ElectronAffinity             17010 non-null  float64
 50  wtd_std_ElectronAffinity         17010 non-null  float64
 51  mean_FusionHeat                  17010 non-null  float64
 52  wtd_mean_FusionHeat              17010 non-null  float64
 53  gmean_FusionHeat                 17010 non-null  float64
 54  wtd_gmean_FusionHeat             17010 non-null  float64
 55  entropy_FusionHeat               17010 non-null  float64
 56  wtd_entropy_FusionHeat           17010 non-null  float64
 57  range_FusionHeat                 17010 non-null  float64
 58  wtd_range_FusionHeat             17010 non-null  float64
 59  std_FusionHeat                   17010 non-null  float64
 60  wtd_std_FusionHeat               17010 non-null  float64
 61  mean_ThermalConductivity         17010 non-null  float64
 62  wtd_mean_ThermalConductivity     17010 non-null  float64
 63  gmean_ThermalConductivity        17010 non-null  float64
 64  wtd_gmean_ThermalConductivity    17010 non-null  float64
 65  entropy_ThermalConductivity      17010 non-null  float64
 66  wtd_entropy_ThermalConductivity  17010 non-null  float64
 67  range_ThermalConductivity        17010 non-null  float64
 68  wtd_range_ThermalConductivity    17010 non-null  float64
 69  std_ThermalConductivity          17010 non-null  float64
 70  wtd_std_ThermalConductivity      17010 non-null  float64
 71  mean_Valence                     17010 non-null  float64
 72  wtd_mean_Valence                 17010 non-null  float64
 73  gmean_Valence                    17010 non-null  float64
 74  wtd_gmean_Valence                17010 non-null  float64
 75  entropy_Valence                  17010 non-null  float64
 76  wtd_entropy_Valence              17010 non-null  float64
 77  range_Valence                    17010 non-null  int64
 78  wtd_range_Valence                17010 non-null  float64
 79  std_Valence                      17010 non-null  float64
 80  wtd_std_Valence                  17010 non-null  float64
 81  critical_temp                    17010 non-null  float64
dtypes: float64(79), int64(3)
memory usage: 10.6 MB

In [ ]:
print(f"Total objects: {len(df)}")

print(f"Total missing values: {df.isna().iloc[:,0].sum()}")

print()

print(f"Number of   numerical columns: {df.dtypes[df.dtypes != "object"].value_counts().sum()}")
print(f"Number of categorical columns: {df.dtypes[df.dtypes == "object"].value_counts().sum()}")

Total objects: 17010
Total missing values: 0

Number of   numerical columns: 82
Number of categorical columns: 0

In [ ]:
df

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,wtd_std_atomic_mass,mean_fie,wtd_mean_fie,gmean_fie,wtd_gmean_fie,entropy_fie,wtd_entropy_fie,range_fie,wtd_range_fie,std_fie,wtd_std_fie,mean_atomic_radius,wtd_mean_atomic_radius,gmean_atomic_radius,wtd_gmean_atomic_radius,entropy_atomic_radius,wtd_entropy_atomic_radius,range_atomic_radius,wtd_range_atomic_radius,std_atomic_radius,wtd_std_atomic_radius,mean_Density,wtd_mean_Density,gmean_Density,wtd_gmean_Density,entropy_Density,wtd_entropy_Density,range_Density,wtd_range_Density,std_Density,wtd_std_Density,mean_ElectronAffinity,wtd_mean_ElectronAffinity,gmean_ElectronAffinity,wtd_gmean_ElectronAffinity,entropy_ElectronAffinity,wtd_entropy_ElectronAffinity,range_ElectronAffinity,wtd_range_ElectronAffinity,std_ElectronAffinity,wtd_std_ElectronAffinity,mean_FusionHeat,wtd_mean_FusionHeat,gmean_FusionHeat,wtd_gmean_FusionHeat,entropy_FusionHeat,wtd_entropy_FusionHeat,range_FusionHeat,wtd_range_FusionHeat,std_FusionHeat,wtd_std_FusionHeat,mean_ThermalConductivity,wtd_mean_ThermalConductivity,gmean_ThermalConductivity,wtd_gmean_ThermalConductivity,entropy_ThermalConductivity,wtd_entropy_ThermalConductivity,range_ThermalConductivity,wtd_range_ThermalConductivity,std_ThermalConductivity,wtd_std_ThermalConductivity,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,53.622535,775.425000,1010.268571,718.152900,938.016780,1.305967,0.791488,810.6,735.985714,323.811808,355.562967,160.250000,105.514286,136.126003,84.528423,1.259244,1.207040,205,42.914286,75.237540,69.235569,4654.35725,2961.502286,724.953211,53.543811,1.033129,0.814598,8958.571,1579.583429,3306.162897,3572.596624,81.837500,111.727143,60.123179,99.414682,1.159687,0.787382,127.05,80.987143,51.433712,42.558396,6.905500,3.846857,3.479475,1.040986,1.088575,0.994998,12.878,1.744571,4.599064,4.666920,107.756645,61.015189,7.062488,0.621979,0.308148,0.262848,399.97342,57.127669,168.854244,138.517163,2.25,2.257143,2.213364,2.219783,1.368922,1.066221,1,1.085714,0.433013,0.437059,29.00
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,53.979870,766.440000,1010.612857,720.605511,938.745413,1.544145,0.807078,810.6,743.164286,290.183029,354.963511,161.200000,104.971429,141.465215,84.370167,1.508328,1.204115,205,50.571429,67.321319,68.008817,5821.48580,3021.016571,1237.095080,54.095718,1.314442,0.914802,10488.571,1667.383429,3767.403176,3632.649185,90.890000,112.316429,69.833315,101.166398,1.427997,0.838666,127.05,81.207857,49.438167,41.667621,7.784400,3.796857,4.403790,1.035251,1.374977,1.073094,12.878,1.595714,4.473363,4.603000,172.205316,61.372331,16.064228,0.619735,0.847404,0.567706,429.97342,51.413383,198.554600,139.630922,2.00,2.257143,1.888175,2.210679,1.557113,1.047221,2,1.128571,0.632456,0.468606,26.00
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,53.656268,775.425000,1010.820000,718.152900,939.009036,1.305967,0.773620,810.6,743.164286,323.811808,354.804183,160.250000,104.685714,136.126003,84.214573,1.259244,1.132547,205,49.314286,75.237540,67.797712,4654.35725,2999.159429,724.953211,53.974022,1.033129,0.760305,8958.571,1667.383429,3306.162897,3592.019281,81.837500,112.213571,60.123179,101.082152,1.159687,0.786007,127.05,81.207857,51.433712,41.639878,6.905500,3.822571,3.479475,1.037439,1.088575,0.927479,12.878,1.757143,4.599064,4.649635,107.756645,60.943760,7.062488,0.619095,0.308148,0.250477,399.97342,57.127669,168.854244,138.540613,2.25,2.271429,2.213364,2.232679,1.368922,1.029175,1,1.114286,0.433013,0.444697,19.00
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,53.639405,775.425000,1010.544286,718.152900,938.512777,1.305967,0.783207,810.6,739.575000,323.811808,355.183884,160.250000,105.100000,136.126003,84.371352,1.259244,1.173033,205,46.114286,75.237540,68.521665,4654.35725,2980.330857,724.953211,53.758486,1.033129,0.788889,8958.571,1623.483429,3306.162897,3582.370597,81.837500,111.970357,60.123179,100.244950,1.159687,0.786900,127.05,81.097500,51.433712,42.102344,6.905500,3.834714,3.479475,1.039211,1.088575,0.964031,12.878,1.744571,4.599064,4.658301,107.756645,60.979474,7.062488,0.620535,0.308148,0.257045,399.97342,57.127669,168.854244,138.528893,2.25,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952,22.00
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,53.588771,775.425000,1009.717143,718.152900,937.025573,1.305967,0.805230,810.6,728.807143,323.811808,356.319281,160.250000,106.342857,136.126003,84.843442,1.259244,1.261194,205,36.514286,75.237540,70.634448,4654.35725,2923.845143,724.953211,53.117029,1.033129,0.859811,8958.571,1491.783429,3306.162897,3552.668664,81.837500,111.240714,60.123179,97.774719,1.159687,0.787396,127.05,80.766429,51.433712,43.452059,6.905500,3.871143,3.479475,1.044545,1.088575,1.044970,12.878,1.744571,4.599064,4.684014,107.756645,61.086617,7.062488,0.624878,0.308148,0.272820,399.97342,57.127669,168.854244,138.493671,2.25,2.242857,2.213364,2.206963,1.368922,1.096052,1,1.057143,0.433013,0.428809,23.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17005,4,106.957877,53.095769,82.515384,43.135565,1.177145,1.254119,146.88130,15.504479,65.764081,43.202659,661.775000,753.793333,651.611213,750.570867,1.371139,0.927050,273.0,427.546667,114.383355,64.428777,176.500000,138.244444,169.947614,134.233861,1.350879,1.112222,111,57.808889,45.883003,35.811330,7341.25000,4963.928889,6404.741690,4082.735787,1.284617,1.110551,7511.000,2449.715556,2981.637585,2978.412680,63.825000,86.511111,49.825259,61.057784,1.164382,0.511822,117.90,74.140000,43.467883,55.219027,25.700000,34.448000,22.494622,29.041737,1.245563,0.631341,36.400,27.497778,14.446107,17.657417,65.500000,111.537778,42.371302,95.001493,1.029002,0.634332,134.00000,83.048889,55.056789,46.595943,3.25,3.555556,3.223710,3.519911,1.377820,0.913658,1,2.168889,0.433013,0.496904,2.44
17006,5,92.266740,49.021367,64.812662,32.867748,1.323287,1.571630,188.38390,7.353333,69.232655,50.148287,747.780000,989.819048,702.115184,923.426093,1.541006,0.988470,810.6,659.771429,293.286136,345.450969,159.200000,112.000000,139.743372,89.633687,1.507321,1.536691,205,20.285714,67.211309,72.795212,5174.28580,2827.415190,962.364248,66.286408,1.165065,1.080432,11848.571,1705.918143,4506.895480,3937.105612,60.484000,100.490952,29.177546,60.814837,1.112639,0.693424,138.63,74.090000,58.434336,57.634544,6.812400,4.793429,3.839585,1.315769,1.345508,1.203223,12.878,2.378952,4.340205,5.204855,132.805316,108.680590,17.747413,1.577047,0.949904,0.745515,399.97342,76.176553,151.164639,156.558695,2.20,2.047619,2.168944,2.038991,1.594167,1.337246,1,0.904762,0.400000,0.212959,122.10
17007,2,99.663190,95.609104,99.433882,95.464320,0.690847,0.530198,13.51362,53.041104,6.756810,5.405448,733.550000,691.580000,730.207231,689.480961,0.688594,0.542120,139.9,370.180000,69.950000,55.960000,183.500000,192.200000,182.926215,191.826893,0.690022,0.465055,29,124.600000,14.500000,11.600000,10296.50000,9260.600000,10150.719679,9170.377777,0.679023,0.572700,3453.000,4451.400000,1726.500000,1381.200000,71.400000,81.120000,69.537903,79.871364,0.667182,0.397810,32.40,59.040000,16.200000,12.960000,21.750000,24.780000,21.155614,24.380978,0.665945,0.395385,10.100,18.100000,5.050000,4.040000,62.500000,57.400000,61.919302,57.038314,0.683870,0.559446,17.00000,29.000000,8.500000,6.800000,4.50,4.800000,4.472136,4.781762,0.686962,0.450561,1,3.200000,0.500000,0.400000,1.98
17008,2,99.663190,97.095602,99.433882,96.901083,0.690847,0.640883,13.51362,31.115202,6.756810,6.249958,733.550000,706.969000,730.207231,704.143255,0.688594,0.648876,139.9,208.799000,69.950000,64.702805,183.500000,189.010000,182.926215,188.514109,0.690022,0.590271,29,84.230000,14.500000,13.412304,10296.50000,9640.430000,10150.719679,9518.329826,0.679023,0.667210,3453.000,2186.170000,1726.500000,1596.989169,71.400000,77.556000,69.537903,75.915236,0.667182,0.527718,32.40,43.332000,16.200000,14.984781,21.750000,23.669000,21.155614,23.144890,0.665945,0.525289,10.100,13.315000,5.050000,4.671182,62.500000,59.270000,61.919302,58.781651,0.683870,0.659671,17.00000,15.250000,8.500000,7.862385,4.50,4.690000,4.472136,4.665819,0.686962,0.577601,1,2.210000,0.500000,0.462493,1.84
17009,3,87.468333,86.858500,82.555758,80.458722,1.041270,0.895229,71.75500,43.144000,29.905282,33.927941,856.166667,821.190000,852.858789,818.631908,1.094784,0.968771,181.3,285.510000,74.569624,65.291691,127.333333,137.500000,125.493812,136.084313,1.084025,0.883461,53,67.700000,21.853045,19.345542,6311.00000,6914.900000,6186.508901,6830.731801,1.078970,0.874139,3055.000,3455.100000,1248.208583,1039.909655,135.133333,104.930000,86.530864,57.563783,0.839248,0.747947,179.30,68.080000,83.414480,87.740504,12.233333,14.440000,10.925390,13.816376,1.002899,0.826780,12.100,6.460000,5.062498,3.481724,27.506667,40.752000,4.976422,12.919996,0.194158,0.142553,78.48000,39.448000,36.425359,38.254432,5.00,4.500000,4.762203,4.242641,1.054920,0.970116,3,1.800000,1.414214,1.500000,12.80

In [ ]:
df.head(10)

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,wtd_std_atomic_mass,mean_fie,wtd_mean_fie,gmean_fie,wtd_gmean_fie,entropy_fie,wtd_entropy_fie,range_fie,wtd_range_fie,std_fie,wtd_std_fie,mean_atomic_radius,wtd_mean_atomic_radius,gmean_atomic_radius,wtd_gmean_atomic_radius,entropy_atomic_radius,wtd_entropy_atomic_radius,range_atomic_radius,wtd_range_atomic_radius,std_atomic_radius,wtd_std_atomic_radius,mean_Density,wtd_mean_Density,gmean_Density,wtd_gmean_Density,entropy_Density,wtd_entropy_Density,range_Density,wtd_range_Density,std_Density,wtd_std_Density,mean_ElectronAffinity,wtd_mean_ElectronAffinity,gmean_ElectronAffinity,wtd_gmean_ElectronAffinity,entropy_ElectronAffinity,wtd_entropy_ElectronAffinity,range_ElectronAffinity,wtd_range_ElectronAffinity,std_ElectronAffinity,wtd_std_ElectronAffinity,mean_FusionHeat,wtd_mean_FusionHeat,gmean_FusionHeat,wtd_gmean_FusionHeat,entropy_FusionHeat,wtd_entropy_FusionHeat,range_FusionHeat,wtd_range_FusionHeat,std_FusionHeat,wtd_std_FusionHeat,mean_ThermalConductivity,wtd_mean_ThermalConductivity,gmean_ThermalConductivity,wtd_gmean_ThermalConductivity,entropy_ThermalConductivity,wtd_entropy_ThermalConductivity,range_ThermalConductivity,wtd_range_ThermalConductivity,std_ThermalConductivity,wtd_std_ThermalConductivity,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,53.622535,775.425,1010.268571,718.152900,938.016780,1.305967,0.791488,810.6,735.985714,323.811808,355.562967,160.25,105.514286,136.126003,84.528423,1.259244,1.207040,205,42.914286,75.237540,69.235569,4654.35725,2961.502286,724.953211,53.543811,1.033129,0.814598,8958.571,1579.583429,3306.162897,3572.596624,81.8375,111.727143,60.123179,99.414682,1.159687,0.787382,127.05,80.987143,51.433712,42.558396,6.9055,3.846857,3.479475,1.040986,1.088575,0.994998,12.878,1.744571,4.599064,4.666920,107.756645,61.015189,7.062488,0.621979,0.308148,0.262848,399.97342,57.127669,168.854244,138.517163,2.25,2.257143,2.213364,2.219783,1.368922,1.066221,1,1.085714,0.433013,0.437059,29.0
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,53.979870,766.440,1010.612857,720.605511,938.745413,1.544145,0.807078,810.6,743.164286,290.183029,354.963511,161.20,104.971429,141.465215,84.370167,1.508328,1.204115,205,50.571429,67.321319,68.008817,5821.48580,3021.016571,1237.095080,54.095718,1.314442,0.914802,10488.571,1667.383429,3767.403176,3632.649185,90.8900,112.316429,69.833315,101.166398,1.427997,0.838666,127.05,81.207857,49.438167,41.667621,7.7844,3.796857,4.403790,1.035251,1.374977,1.073094,12.878,1.595714,4.473363,4.603000,172.205316,61.372331,16.064228,0.619735,0.847404,0.567706,429.97342,51.413383,198.554600,139.630922,2.00,2.257143,1.888175,2.210679,1.557113,1.047221,2,1.128571,0.632456,0.468606,26.0
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,53.656268,775.425,1010.820000,718.152900,939.009036,1.305967,0.773620,810.6,743.164286,323.811808,354.804183,160.25,104.685714,136.126003,84.214573,1.259244,1.132547,205,49.314286,75.237540,67.797712,4654.35725,2999.159429,724.953211,53.974022,1.033129,0.760305,8958.571,1667.383429,3306.162897,3592.019281,81.8375,112.213571,60.123179,101.082152,1.159687,0.786007,127.05,81.207857,51.433712,41.639878,6.9055,3.822571,3.479475,1.037439,1.088575,0.927479,12.878,1.757143,4.599064,4.649635,107.756645,60.943760,7.062488,0.619095,0.308148,0.250477,399.97342,57.127669,168.854244,138.540613,2.25,2.271429,2.213364,2.232679,1.368922,1.029175,1,1.114286,0.433013,0.444697,19.0
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,53.639405,775.425,1010.544286,718.152900,938.512777,1.305967,0.783207,810.6,739.575000,323.811808,355.183884,160.25,105.100000,136.126003,84.371352,1.259244,1.173033,205,46.114286,75.237540,68.521665,4654.35725,2980.330857,724.953211,53.758486,1.033129,0.788889,8958.571,1623.483429,3306.162897,3582.370597,81.8375,111.970357,60.123179,100.244950,1.159687,0.786900,127.05,81.097500,51.433712,42.102344,6.9055,3.834714,3.479475,1.039211,1.088575,0.964031,12.878,1.744571,4.599064,4.658301,107.756645,60.979474,7.062488,0.620535,0.308148,0.257045,399.97342,57.127669,168.854244,138.528893,2.25,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952,22.0
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,53.588771,775.425,1009.717143,718.152900,937.025573,1.305967,0.805230,810.6,728.807143,323.811808,356.319281,160.25,106.342857,136.126003,84.843442,1.259244,1.261194,205,36.514286,75.237540,70.634448,4654.35725,2923.845143,724.953211,53.117029,1.033129,0.859811,8958.571,1491.783429,3306.162897,3552.668664,81.8375,111.240714,60.123179,97.774719,1.159687,0.787396,127.05,80.766429,51.433712,43.452059,6.9055,3.871143,3.479475,1.044545,1.088575,1.044970,12.878,1.744571,4.599064,4.684014,107.756645,61.086617,7.062488,0.624878,0.308148,0.272820,399.97342,57.127669,168.854244,138.493671,2.25,2.242857,2.213364,2.206963,1.368922,1.096052,1,1.057143,0.433013,0.428809,23.0
5,4,88.944468,57.795044,66.361592,36.098926,1.181795,1.225203,122.90607,20.687458,51.968828,53.521150,775.425,1008.614286,718.152900,935.046300,1.305967,0.824743,810.6,714.450000,323.811808,357.824566,160.25,108.000000,136.126003,85.477006,1.259244,1.331339,205,23.714286,75.237540,73.324134,4654.35725,2848.530857,724.953211,52.273642,1.033129,0.932369,8958.571,1316.183429,3306.162897,3511.262204,81.8375,110.267857,60.123179,94.575505,1.159687,0.784461,127.05,80.325000,51.433712,45.170683,6.9055,3.919714,3.479475,1.051699,1.088575,1.111850,12.878,1.744571,4.599064,4.717642,107.756645,61.229474,7.062488,0.630715,0.308148,0.288236,399.97342,57.127669,168.854244,138.446567,2.25,2.214286,2.213364,2.181543,1.368922,1.141474,1,1.000000,0.433013,0.410326,23.0
6,4,88.944468,57.682296,66.361592,36.069470,1.181795,1.316857,122.90607,10.765639,51.968828,53.351558,775.425,1005.857143,718.152900,930.116389,1.305967,0.841872,810.6,678.557143,323.811808,361.545642,160.25,112.142857,136.126003,87.081694,1.259244,1.367279,205,15.428571,75.237540,79.500995,4654.35725,2660.245143,724.953211,50.223298,1.033129,1.034877,8958.571,1279.183429,3306.162897,3398.249436,81.8375,107.835714,60.123179,87.027980,1.159687,0.762603,127.05,79.221429,51.433712,49.121095,6.9055,4.041143,3.479475,1.069798,1.088575,1.156821,12.878,1.744571,4.599064,4.798531,107.756645,61.586617,7.062488,0.645547,0.308148,0.309727,399.97342,57.127669,168.854244,138.328090,2.25,2.142857,2.213364,2.119268,1.368922,1.194453,1,0.857143,0.433013,0.349927,11.0
7,4,76.517718,57.175142,59.310096,35.891368,1.197273,0.943560,122.90607,36.451199,44.289459,52.924140,787.050,1011.484286,734.219624,940.197000,1.313008,0.776332,772.0,742.500000,314.505966,353.894217,151.75,104.200000,131.302197,84.041128,1.275274,1.121818,171,49.800000,65.579627,66.848571,4434.35725,2986.588000,674.484751,53.751929,0.995983,0.745715,8958.571,1667.383429,3402.856196,3591.749343,79.6075,112.086143,48.477265,99.846169,1.096672,0.779397,135.97,81.335286,54.373097,41.948310,6.9055,3.822571,3.479475,1.037439,1.088575,0.927479,12.878,1.757143,4.599064,4.649635,112.006645,61.186617,8.339818,0.625004,0.403693,0.269730,399.97342,57.127669,166.742351,138.480008,2.25,2.271429,2.213364,2.232679,1.368922,1.029175,1,1.114286,0.433013,0.444697,33.0
8,4,76.517718,56.808817,59.310096,35.773432,1.197273,0.981880,122.90607,34.833160,44.289459,52.533207,787.050,1011.540714,734.219624,940.294344,1.313008,0.786865,772.0,738.578571,314.505966,353.819831,151.75,104.371429,131.302197,84.110835,1.275274,1.160060,171,46.842857,65.579627,67.111458,4434.35725,2961.473714,674.484751,53.427017,0.995983,0.769628,8958.571,1623.483429,3402.856196,3581.848921,79.6075,111.779214,48.477265,98.411962,1.096672,0.777657,135.97,81.288643,54.373097,42.557892,6.9055,3.834714,3.479475,1.039211,1.088575,0.964031,12.878,1.744571,4.599064,4.658301,112.006645,61.343760,8.339818,0.629441,0.403693,0.283412,399.97342,57.127669,166.742351,138.437714,2.25,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952,36.0
9,4,76.517718,56.442492,59.310096,35.655884,1.197273,1.016495,122.90607,33.215121,44.289459,52.136769,787.050,1011.597143,734.219624,940.391699,1.313008,0.795977,772.0,734.657143,314.505966,353.745421,151.75,104.542857,131.302197,84.180599,1.275274,1.192734,171,43.885714,65.579627,67.372883,4434.35725,2936.359429,674.484751,53.104070,0.995983,0.791445,8958.571,1579.583429,3402.856196,3571.744474,79.6075,111.472286,48.477265,96.998357,1.096672,0.775688,135.97,81.242000,54.373097,43.156683,6.9055,3.846857,3.479475,1.040986,1.088575,0.994998,12.878,1.744571,4.599064,4.666920,112.006645,61.500903,8.339818,0.633910,0.403693,0.295609,399.97342,57.127669,166.742351,138.395229,2.25,2.257143,2.213364,2.219783,1.368922,1.066221,1,1.085714,0.433013,0.437059,31.0

In [ ]:
df.sample(10)

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,wtd_std_atomic_mass,mean_fie,wtd_mean_fie,gmean_fie,wtd_gmean_fie,entropy_fie,wtd_entropy_fie,range_fie,wtd_range_fie,std_fie,wtd_std_fie,mean_atomic_radius,wtd_mean_atomic_radius,gmean_atomic_radius,wtd_gmean_atomic_radius,entropy_atomic_radius,wtd_entropy_atomic_radius,range_atomic_radius,wtd_range_atomic_radius,std_atomic_radius,wtd_std_atomic_radius,mean_Density,wtd_mean_Density,gmean_Density,wtd_gmean_Density,entropy_Density,wtd_entropy_Density,range_Density,wtd_range_Density,std_Density,wtd_std_Density,mean_ElectronAffinity,wtd_mean_ElectronAffinity,gmean_ElectronAffinity,wtd_gmean_ElectronAffinity,entropy_ElectronAffinity,wtd_entropy_ElectronAffinity,range_ElectronAffinity,wtd_range_ElectronAffinity,std_ElectronAffinity,wtd_std_ElectronAffinity,mean_FusionHeat,wtd_mean_FusionHeat,gmean_FusionHeat,wtd_gmean_FusionHeat,entropy_FusionHeat,wtd_entropy_FusionHeat,range_FusionHeat,wtd_range_FusionHeat,std_FusionHeat,wtd_std_FusionHeat,mean_ThermalConductivity,wtd_mean_ThermalConductivity,gmean_ThermalConductivity,wtd_gmean_ThermalConductivity,entropy_ThermalConductivity,wtd_entropy_ThermalConductivity,range_ThermalConductivity,wtd_range_ThermalConductivity,std_ThermalConductivity,wtd_std_ThermalConductivity,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
13045,2,97.905940,95.406160,97.778206,95.311170,0.691843,0.582911,9.999120,43.953410,4.999560,4.329746,691.550000,677.575000,690.984949,677.154054,0.692330,0.578700,55.9,317.825000,27.950000,24.205410,185.500000,191.750000,185.078362,191.430185,0.690875,0.533848,25,105.250000,12.500000,10.825318,10510.000000,9540.000000,10329.399789,9408.663890,0.676013,0.631497,3880.000,3315.000000,1940.000000,1680.089283,99.400000,93.500000,98.697112,92.983155,0.686084,0.608582,23.60,37.900000,11.800000,10.219100,24.250000,25.525000,24.115555,25.422370,0.687608,0.517298,5.100,14.675000,2.550000,2.208365,102.000000,78.000000,90.000000,69.713700,0.577922,0.692407,96.00000,3.000000,48.000000,41.569219,5.500000,5.250000,5.477226,5.233176,0.689009,0.598270,1,2.250000,0.500000,0.433013,2.797
14806,2,141.720500,124.888333,132.419045,116.950838,0.628252,0.692807,100.993000,3.256333,50.496500,47.608557,763.900000,729.166667,756.759916,722.915564,0.683815,0.671712,208.4,150.433333,104.200000,98.240702,193.000000,197.333333,192.561678,196.940778,0.690877,0.614260,26,77.333333,13.000000,12.256518,14535.500000,11860.666667,12119.742572,9852.463365,0.531886,0.656777,16049.000,3179.333333,8024.500000,7565.571154,97.550000,79.233333,80.600868,65.167293,0.524811,0.652512,109.90,22.433333,54.950000,51.807357,23.500000,22.666667,23.366643,22.549521,0.687478,0.665204,5.000,5.333333,2.500000,2.357023,86.500000,65.333333,58.736701,42.971678,0.391953,0.544886,127.00000,34.666667,63.500000,59.868374,5.000000,4.666667,4.898979,4.578857,0.673012,0.682908,2,0.666667,1.000000,0.942809,7.500
5058,4,88.944468,57.871712,66.361592,36.118971,1.181795,1.030748,122.906070,33.373392,51.968828,53.636031,775.425000,1010.489143,718.152900,938.413556,1.305967,0.784955,810.6,738.857143,323.811808,355.259750,160.250000,105.182857,136.126003,84.402743,1.259244,1.180289,205,45.474286,75.237540,68.665240,4654.357250,2976.565143,724.953211,53.715482,1.033129,0.794232,8958.571,1614.703429,3306.162897,3580.425858,81.837500,111.921714,60.123179,100.078344,1.159687,0.787026,127.05,81.075429,51.433712,42.194061,6.905500,3.837143,3.479475,1.039566,1.088575,0.970617,12.878,1.744571,4.599064,4.660029,107.756645,60.986617,7.062488,0.620824,0.308148,0.258259,399.97342,57.127669,168.854244,138.526547,2.250000,2.262857,2.213364,2.224933,1.368922,1.052472,1,1.097143,0.433013,0.440185,26.100
10102,2,94.612000,97.032000,94.551319,97.002024,0.692506,0.394491,6.776000,70.968000,3.388000,2.371106,680.950000,696.128571,680.618351,695.964917,0.692660,0.396490,42.5,507.642857,21.250000,14.871902,194.500000,186.285714,194.159728,186.121375,0.691398,0.436297,23,127.428571,11.500000,8.048323,9005.500000,10787.285714,8653.120824,10602.418982,0.654277,0.293718,4989.000,8927.000000,2494.500000,1745.786332,48.550000,52.800000,48.184022,52.615374,0.685619,0.357373,11.90,40.628571,5.950000,4.164133,22.000000,22.714286,21.977261,22.703027,0.692114,0.390313,2.000,16.714286,1.000000,0.699854,37.000000,47.000000,34.249088,45.516004,0.619748,0.253403,28.00000,40.428571,14.000000,9.797959,5.000000,5.714286,4.898979,5.662332,0.673012,0.325083,2,4.571429,1.000000,0.699854,9.700
1325,5,84.519360,59.339941,65.504650,36.494463,1.415945,1.015824,128.242600,38.070791,49.919189,55.863837,773.180000,1008.805314,729.601077,935.519124,1.547681,0.787031,781.6,749.711829,285.100245,357.455884,146.600000,106.553429,131.633640,85.033600,1.527104,1.140591,158,54.315143,54.282962,70.115185,6313.685800,3276.750571,1398.427424,56.434342,1.377862,0.842815,8958.571,1851.826286,3292.529275,3831.019379,95.780000,113.265943,87.548533,103.942433,1.528207,0.827907,91.00,81.331286,37.416488,39.807269,8.624400,3.996086,4.551502,1.064239,1.315345,0.945019,16.978,1.861686,5.937304,4.759466,103.805316,61.621760,11.258994,0.658299,0.700180,0.297805,399.97342,56.784811,151.534341,137.872508,2.600000,2.307143,2.491462,2.259535,1.564957,1.100585,2,1.141143,0.800000,0.505632,8.400
7569,7,111.027045,115.396011,83.970385,86.096248,1.731402,1.445364,192.981000,55.544980,70.305326,72.372858,754.728571,760.516000,724.441440,725.422560,1.900994,1.650347,772.0,216.460667,240.690078,259.035324,152.142857,152.020000,139.994214,137.393060,1.882120,1.571267,171,57.863333,49.812301,56.152824,6618.204143,5963.671500,2085.287140,1524.938573,1.716010,1.427269,11338.571,2607.761833,3749.520646,4021.852141,64.175714,75.540000,31.094699,45.516317,1.570283,1.414502,141.00,24.715000,51.102970,50.810840,8.070286,7.998667,5.183861,4.934881,1.747990,1.409505,12.978,2.869667,4.395543,4.189531,71.246654,80.030097,10.060295,9.889177,0.776091,0.668062,399.97342,65.328903,134.806576,142.004864,3.142857,3.006667,2.944713,2.753968,1.882303,1.571549,3,1.320000,1.124858,1.316544,26.100
11097,2,81.314690,88.269704,80.484232,87.722630,0.682952,0.436300,23.183380,60.380504,11.591690,9.273352,621.150000,646.620000,619.697765,645.677716,0.690810,0.469862,84.9,415.140000,42.450000,33.960000,167.000000,185.600000,164.097532,183.670722,0.675818,0.416681,62,131.200000,31.000000,24.800000,7237.000000,8036.800000,7113.176506,7954.519069,0.676087,0.417336,2666.000,5675.200000,1333.000000,1066.400000,59.000000,76.160000,51.604651,70.888862,0.570560,0.278359,57.20,64.000000,28.600000,22.880000,16.195000,22.558000,12.239771,19.588005,0.459960,0.197221,21.210,20.322000,10.605000,8.484000,41.500000,49.000000,39.572718,47.686408,0.647073,0.363659,25.00000,37.400000,12.500000,10.000000,4.000000,4.600000,3.872983,4.514402,0.661563,0.387212,2,3.400000,1.000000,0.800000,15.300
11404,3,20.699180,15.844308,19.210680,14.461611,1.033671,1.049757,16.170539,3.966667,7.076865,7.158316,704.900000,747.213333,698.323035,741.452830,1.089514,0.795945,223.0,435.160000,93.877828,87.554180,116.666667,100.933333,114.179925,98.985513,1.077644,0.974700,58,38.666667,23.697163,21.132808,2299.333333,2411.733333,2260.040462,2392.780131,1.082169,0.822409,962.000,1408.266667,408.836832,280.526046,24.566667,27.800000,12.300734,20.845010,0.754800,0.664157,42.50,18.600000,17.539733,12.034118,23.133333,36.633333,16.696458,29.093278,0.784791,0.361135,41.300,32.173333,19.015140,18.911784,140.666667,86.333333,100.504121,52.764126,0.869607,1.003358,208.00000,29.000000,86.009043,86.549921,2.666667,2.866667,2.620741,2.842120,1.082196,0.799430,1,1.733333,0.471405,0.339935,12.000
5712,4,76.444563,51.245665,59.356672,34.935266,1.199541,1.291888,121.327600,14.288319,43.823354,44.192125,794.000000,1003.623077,741.629349,937.559192,1.315004,0.890516,810.6,659.715385,311.743492,342.396001,164.500000,114.538462,139.000514,89.685191,1.256701,1.339743,205,22.615385,77.525802,79.235399,4235.857250,2952.461769,669.556588,66.342169,1.015407,0.812798,8958.571,2066.922846,3194.938946,3639.129247,77.237500,109.169231,53.527965,86.539377,1.105182,0.762761,127.05,74.353846,54.830755,49.445714,8.180500,5.250308,4.035569,1.336920,1.112098,1.042927,12.878,2.903538,4.948155,5.648557,108.756645,96.398928,7.552385,1.096295,0.336262,0.203148,399.97342,92.293380,168.301047,166.440383,2.250000,2.076923,2.213364,2.063362,1.368922,1.201823,1,0.846154,0.433013,0.266469,78.000
15852,4,76.797975,76.039349,68.845615,71.689408,1.276357,1.163298,98.228700,28.482905,37.173836,28.705075,656.575000,779.428000,623.416605,758.090832,1.335639,1.033397,527.7,362.577000,209.053120,169.305377,191.500000,158.220000,181.839849,151.345789,1.337702,1.241215,139,53.166000,58.525635,50.125359,4491.750000,6041.548000,3411.739540,5590.141401,1.190014,0.957838,7018.000,3117.072000,2605.185634,1855.467578,40.512500,43.079100,32.042851,32.470761,1.174229,0.819859,64.05,29.903800,26.361676,30.396008,12.957500,17.984540,9.187581,15.602840,1.115044,0.876639,25.370,10.991460,9.428304,8.379894,61.750000,58.316000,51.637761,52.238775,1.244889,1.026777,82.00000,28.684000,30.873735,22.981126,2.750000,3.562000,2.340347,3.305243,1.240684,0.957110,4,1.962000,1.479020,1.264182,15.000

In [ ]:
df.describe()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,wtd_std_atomic_mass,mean_fie,wtd_mean_fie,gmean_fie,wtd_gmean_fie,entropy_fie,wtd_entropy_fie,range_fie,wtd_range_fie,std_fie,wtd_std_fie,mean_atomic_radius,wtd_mean_atomic_radius,gmean_atomic_radius,wtd_gmean_atomic_radius,entropy_atomic_radius,wtd_entropy_atomic_radius,range_atomic_radius,wtd_range_atomic_radius,std_atomic_radius,wtd_std_atomic_radius,mean_Density,wtd_mean_Density,gmean_Density,wtd_gmean_Density,entropy_Density,wtd_entropy_Density,range_Density,wtd_range_Density,std_Density,wtd_std_Density,mean_ElectronAffinity,wtd_mean_ElectronAffinity,gmean_ElectronAffinity,wtd_gmean_ElectronAffinity,entropy_ElectronAffinity,wtd_entropy_ElectronAffinity,range_ElectronAffinity,wtd_range_ElectronAffinity,std_ElectronAffinity,wtd_std_ElectronAffinity,mean_FusionHeat,wtd_mean_FusionHeat,gmean_FusionHeat,wtd_gmean_FusionHeat,entropy_FusionHeat,wtd_entropy_FusionHeat,range_FusionHeat,wtd_range_FusionHeat,std_FusionHeat,wtd_std_FusionHeat,mean_ThermalConductivity,wtd_mean_ThermalConductivity,gmean_ThermalConductivity,wtd_gmean_ThermalConductivity,entropy_ThermalConductivity,wtd_entropy_ThermalConductivity,range_ThermalConductivity,wtd_range_ThermalConductivity,std_ThermalConductivity,wtd_std_ThermalConductivity,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
count,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000,17010.000000
mean,4.113874,87.534919,73.000381,71.308789,58.599393,1.165500,1.063972,115.443468,33.228642,44.320187,41.347802,769.945102,870.933167,737.791166,833.187164,1.298859,0.925990,572.564891,484.011001,215.783192,224.335460,157.931593,134.658921,144.381822,120.903678,1.267346,1.130936,139.402293,51.369816,51.628650,52.381817,6108.635376,5265.400936,3460.446536,3120.293657,1.072023,0.856086,8658.461969,2900.952855,3412.752366,3312.148043,77.003663,92.830366,54.420073,72.480817,1.069598,0.770660,120.962755,59.372269,48.985877,44.469852,14.325644,13.859314,10.169378,10.151939,1.093428,0.914854,21.132295,8.200406,8.317290,7.717151,89.876640,81.592442,29.851146,27.324396,0.727474,0.540722,251.268731,62.041541,99.092786,96.275334,3.197028,3.151430,3.055206,3.054358,1.295344,1.052631,2.042034,1.482988,0.839731,0.673590,34.502993
std,1.437846,29.786319,33.730910,31.166777,36.902657,0.364607,0.401877,54.614167,27.104426,19.993413,19.930640,87.402203,143.051039,78.290392,119.510733,0.382058,0.333773,309.303523,223.827363,109.825004,127.914578,20.105135,28.762215,22.047738,35.809683,0.375528,0.407911,67.264931,35.081827,22.905399,25.319727,2855.693051,3242.812464,3712.571509,3995.713727,0.341475,0.319447,4088.612125,2417.426098,1665.215317,1603.135763,27.748074,32.309955,29.158061,31.701324,0.342165,0.284759,58.926401,28.668109,21.759314,20.476811,11.397846,14.328290,10.153209,13.165483,0.374916,0.369689,20.425096,11.405526,8.700649,7.337987,38.482464,45.521662,34.036993,40.275268,0.325412,0.318095,158.606516,43.159218,60.130999,63.657435,1.044669,1.192035,1.045869,1.175579,0.393231,0.380725,1.244305,0.980906,0.485728,0.454975,34.334793
min,1.000000,6.941000,6.423452,5.320573,1.960849,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,496.850000,502.500000,490.633468,502.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,48.000000,48.000000,48.000000,48.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.429000,1.429000,1.429000,0.686245,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.500000,1.500000,1.500000,1.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.222000,0.222000,0.222000,0.222000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.026580,0.026580,0.026580,0.022952,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000210
25%,3.000000,72.383174,52.078254,58.001648,35.228269,0.966676,0.777721,78.353150,16.790394,32.890369,28.541193,724.366667,739.456147,692.541331,721.133733,1.085896,0.754997,265.425000,291.268750,114.533906,94.187041,149.285714,112.113523,133.542493,89.193073,1.066992,0.853635,80.000000,28.500000,35.152045,32.030016,4516.333333,2998.244640,883.117278,66.648166,0.914238,0.688583,6648.000000,1652.000000,2814.892797,2566.450918,62.090000,73.514375,33.700512,50.875182,0.894571,0.661378,87.000000,34.036000,38.653072,33.492891,7.588667,5.027231,4.109878,1.321875,0.836804,0.673889,12.878000,2.311978,4.257342,4.607295,61.000000,54.328986,8.375335,1.086838,0.457810,0.251213,87.000000,29.424100,38.274530,32.055507,2.333333,2.117647,2.245649,2.091629,1.060857,0.779166,1.000000,0.920000,0.451754,0.307467,5.330000
50%,4.000000,84.841880,60.547264,66.361592,39.821155,1.199541,1.148646,122.906070,26.585389,45.123500,44.283971,765.533333,891.110417,728.541241,857.386367,1.355088,0.916945,764.100000,512.819200,266.335760,258.749180,160.250000,125.833333,142.807563,113.166222,1.329628,1.243541,171.000000,43.023707,58.666515,60.313364,5329.085800,4284.938167,1339.890281,1510.882513,1.090503,0.882747,8958.571000,2082.363003,3294.078198,3623.317348,73.100000,103.063248,51.449769,73.113898,1.135725,0.780932,127.050000,71.170312,51.125720,48.058738,9.304400,8.283833,5.272119,4.900190,1.112098,0.994998,12.878000,3.426016,4.948155,5.498409,96.666667,73.114375,14.287643,6.090740,0.738694,0.548231,399.795000,56.441954,135.782279,114.175102,2.833333,2.605455,2.615321,2.429201,1.368922,1.168512,2.000000,1.062857,0.800000,0.500000,20.000000
75%,5.000000,100.404410,85.982586,78.116681,73.075297,1.444537,1.359836,154.119320,38.193007,58.973428,53.591995,796.320000,1004.216538,765.715174,937.599759,1.551120,1.061059,810.600000,690.749249,297.946646,342.678174,169.750000,158.244500,155.938199,150.976969,1.512247,1.424885,205.000000,60.262481,69.424491,73.841852,6728.000000,6386.368344,5770.285523,5763.290727,1.323514,1.080677,9778.571000,3382.815789,4004.273231,3957.263723,85.640000,110.738462,67.530058,90.047057,1.343521,0.876999,138.630000,76.711010,56.588830,53.339886,17.100000,18.498409,13.649683,16.429440,1.378110,1.156951,23.200000,10.440000,9.034950,8.012010,111.005316,99.051743,42.319281,47.266398,0.959607,0.777361,399.973420,91.797724,153.876488,162.513347,4.000000,4.019566,3.722419,3.914868,1.589027,1.331531,3.000000,1.912000,1.200000,1.020735,63.000000
max,9.000000,208.980400,208.980400,208.980400,208.980400,1.983797,1.958203,207.972460,205.589910,101.019700,101.019700,1313.100000,1313.100000,1313.100000,1313.100000,2.157777,2.038560,1304.500000,1049.395122,499.671949,479.162305,253.000000,253.000000,253.000000,253.000000,2.141961,1.903748,256.000000,240.164344,115.500000,97.140711,22590.000000,22590.000000,22590.000000,22590.000000,1.954297,1.703420,22588.571000,22248.700000,10724.374500,10410.932005,326.100000,326.100000,326.100000,326.100000,1.767732,1.675400,349.000000,218.696600,155.684368,169.075862,105.000000,105.000000,105.000000,105.000000,2.034410,1.745105,104.778000,102.385610,51.635000,51.680482,332.500000,389.900000,317.883627,373.632858,1.633977,1.612989,429.974170,384.100000,214.775500,213.300452,7.000000,7.000000,7.000000,7.000000,2.141963,1.949739,6.000000,6.992200,3.000000,3.000000,185.000000

In [ ]:
float64_cols = df.select_dtypes(include=['float64']).columns
int64_cols = df.select_dtypes(include=['int64']).columns

# df[float64_cols] = df[float64_cols].astype(np.float32)
# df[int64_cols] = df[int64_cols].astype(np.int32)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17010 entries, 0 to 17009
Data columns (total 82 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   number_of_elements               17010 non-null  int64
 1   mean_atomic_mass                 17010 non-null  float64
 2   wtd_mean_atomic_mass             17010 non-null  float64
 3   gmean_atomic_mass                17010 non-null  float64
 4   wtd_gmean_atomic_mass            17010 non-null  float64
 5   entropy_atomic_mass              17010 non-null  float64
 6   wtd_entropy_atomic_mass          17010 non-null  float64
 7   range_atomic_mass                17010 non-null  float64
 8   wtd_range_atomic_mass            17010 non-null  float64
 9   std_atomic_mass                  17010 non-null  float64
 10  wtd_std_atomic_mass              17010 non-null  float64
 11  mean_fie                         17010 non-null  float64
 12  wtd_mean_fie                     17010 non-null  float64
 13  gmean_fie                        17010 non-null  float64
 14  wtd_gmean_fie                    17010 non-null  float64
 15  entropy_fie                      17010 non-null  float64
 16  wtd_entropy_fie                  17010 non-null  float64
 17  range_fie                        17010 non-null  float64
 18  wtd_range_fie                    17010 non-null  float64
 19  std_fie                          17010 non-null  float64
 20  wtd_std_fie                      17010 non-null  float64
 21  mean_atomic_radius               17010 non-null  float64
 22  wtd_mean_atomic_radius           17010 non-null  float64
 23  gmean_atomic_radius              17010 non-null  float64
 24  wtd_gmean_atomic_radius          17010 non-null  float64
 25  entropy_atomic_radius            17010 non-null  float64
 26  wtd_entropy_atomic_radius        17010 non-null  float64
 27  range_atomic_radius              17010 non-null  int64
 28  wtd_range_atomic_radius          17010 non-null  float64
 29  std_atomic_radius                17010 non-null  float64
 30  wtd_std_atomic_radius            17010 non-null  float64
 31  mean_Density                     17010 non-null  float64
 32  wtd_mean_Density                 17010 non-null  float64
 33  gmean_Density                    17010 non-null  float64
 34  wtd_gmean_Density                17010 non-null  float64
 35  entropy_Density                  17010 non-null  float64
 36  wtd_entropy_Density              17010 non-null  float64
 37  range_Density                    17010 non-null  float64
 38  wtd_range_Density                17010 non-null  float64
 39  std_Density                      17010 non-null  float64
 40  wtd_std_Density                  17010 non-null  float64
 41  mean_ElectronAffinity            17010 non-null  float64
 42  wtd_mean_ElectronAffinity        17010 non-null  float64
 43  gmean_ElectronAffinity           17010 non-null  float64
 44  wtd_gmean_ElectronAffinity       17010 non-null  float64
 45  entropy_ElectronAffinity         17010 non-null  float64
 46  wtd_entropy_ElectronAffinity     17010 non-null  float64
 47  range_ElectronAffinity           17010 non-null  float64
 48  wtd_range_ElectronAffinity       17010 non-null  float64
 49  std_ElectronAffinity             17010 non-null  float64
 50  wtd_std_ElectronAffinity         17010 non-null  float64
 51  mean_FusionHeat                  17010 non-null  float64
 52  wtd_mean_FusionHeat              17010 non-null  float64
 53  gmean_FusionHeat                 17010 non-null  float64
 54  wtd_gmean_FusionHeat             17010 non-null  float64
 55  entropy_FusionHeat               17010 non-null  float64
 56  wtd_entropy_FusionHeat           17010 non-null  float64
 57  range_FusionHeat                 17010 non-null  float64
 58  wtd_range_FusionHeat             17010 non-null  float64
 59  std_FusionHeat                   17010 non-null  float64
 60  wtd_std_FusionHeat               17010 non-null  float64
 61  mean_ThermalConductivity         17010 non-null  float64
 62  wtd_mean_ThermalConductivity     17010 non-null  float64
 63  gmean_ThermalConductivity        17010 non-null  float64
 64  wtd_gmean_ThermalConductivity    17010 non-null  float64
 65  entropy_ThermalConductivity      17010 non-null  float64
 66  wtd_entropy_ThermalConductivity  17010 non-null  float64
 67  range_ThermalConductivity        17010 non-null  float64
 68  wtd_range_ThermalConductivity    17010 non-null  float64
 69  std_ThermalConductivity          17010 non-null  float64
 70  wtd_std_ThermalConductivity      17010 non-null  float64
 71  mean_Valence                     17010 non-null  float64
 72  wtd_mean_Valence                 17010 non-null  float64
 73  gmean_Valence                    17010 non-null  float64
 74  wtd_gmean_Valence                17010 non-null  float64
 75  entropy_Valence                  17010 non-null  float64
 76  wtd_entropy_Valence              17010 non-null  float64
 77  range_Valence                    17010 non-null  int64
 78  wtd_range_Valence                17010 non-null  float64
 79  std_Valence                      17010 non-null  float64
 80  wtd_std_Valence                  17010 non-null  float64
 81  critical_temp                    17010 non-null  float64
dtypes: float64(79), int64(3)
memory usage: 10.6 MB

In [ ]:
def get_num_outliers(column):
    q1 = np.percentile(column, 25)
    q3 = np.percentile(column, 75)
    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    return ((column < lower) | (column > upper)).sum()


print("Number of outliers for each column:")

max_col_width = max(len(col) for col in df.columns)

for column in df.columns:
    print(f"{column:<{max_col_width}}: {get_num_outliers(df[column])}")

Number of outliers for each column:
number_of_elements             : 11
mean_atomic_mass               : 1285
wtd_mean_atomic_mass           : 1028
gmean_atomic_mass              : 2668
wtd_gmean_atomic_mass          : 1022
entropy_atomic_mass            : 314
wtd_entropy_atomic_mass        : 0
range_atomic_mass              : 0
wtd_range_atomic_mass          : 1315
std_atomic_mass                : 3
wtd_std_atomic_mass            : 7
mean_fie                       : 1552
wtd_mean_fie                   : 0
gmean_fie                      : 1194
wtd_gmean_fie                  : 2
entropy_fie                    : 235
wtd_entropy_fie                : 1764
range_fie                      : 0
wtd_range_fie                  : 0
std_fie                        : 0
wtd_std_fie                    : 0
mean_atomic_radius             : 967
wtd_mean_atomic_radius         : 10
gmean_atomic_radius            : 1205
wtd_gmean_atomic_radius        : 7
entropy_atomic_radius          : 235
wtd_entropy_atomic_radius      : 0
range_atomic_radius            : 0
wtd_range_atomic_radius        : 1495
std_atomic_radius              : 0
wtd_std_atomic_radius          : 0
mean_Density                   : 1458
wtd_mean_Density               : 776
gmean_Density                  : 405
wtd_gmean_Density              : 362
entropy_Density                : 473
wtd_entropy_Density            : 595
range_Density                  : 2315
wtd_range_Density              : 1400
std_Density                    : 2753
wtd_std_Density                : 1826
mean_ElectronAffinity          : 1761
wtd_mean_ElectronAffinity      : 439
gmean_ElectronAffinity         : 661
wtd_gmean_ElectronAffinity     : 283
entropy_ElectronAffinity       : 444
wtd_entropy_ElectronAffinity   : 2727
range_ElectronAffinity         : 1246
wtd_range_ElectronAffinity     : 135
std_ElectronAffinity           : 1953
wtd_std_ElectronAffinity       : 1184
mean_FusionHeat                : 1331
wtd_mean_FusionHeat            : 956
gmean_FusionHeat               : 1187
wtd_gmean_FusionHeat           : 471
entropy_FusionHeat             : 235
wtd_entropy_FusionHeat         : 0
range_FusionHeat               : 1691
wtd_range_FusionHeat           : 1112
std_FusionHeat                 : 1667
wtd_std_FusionHeat             : 2104
mean_ThermalConductivity       : 239
wtd_mean_ThermalConductivity   : 1148
gmean_ThermalConductivity      : 999
wtd_gmean_ThermalConductivity  : 701
entropy_ThermalConductivity    : 0
wtd_entropy_ThermalConductivity: 3
range_ThermalConductivity      : 0
wtd_range_ThermalConductivity  : 161
std_ThermalConductivity        : 0
wtd_std_ThermalConductivity    : 0
mean_Valence                   : 6
wtd_mean_Valence               : 28
gmean_Valence                  : 368
wtd_gmean_Valence              : 45
entropy_Valence                : 235
wtd_entropy_Valence            : 0
range_Valence                  : 0
wtd_range_Valence              : 1169
std_Valence                    : 32
wtd_std_Valence                : 19
critical_temp                  : 1

In [ ]:
corr_matrix = df.corr()
upper_triangle = np.triu(np.ones_like(corr_matrix, dtype=bool), k=1)

high_corr = corr_matrix.where(upper_triangle) > 0.9

num_high_corr_pairs = high_corr.sum().sum()

print(f"Число пар признаков с корреляцией > 0.9: {num_high_corr_pairs}")

Число пар признаков с корреляцией > 0.9: 73

In [ ]:
df.corr().where(lambda x: x > 0.9)

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,wtd_std_atomic_mass,mean_fie,wtd_mean_fie,gmean_fie,wtd_gmean_fie,entropy_fie,wtd_entropy_fie,range_fie,wtd_range_fie,std_fie,wtd_std_fie,mean_atomic_radius,wtd_mean_atomic_radius,gmean_atomic_radius,wtd_gmean_atomic_radius,entropy_atomic_radius,wtd_entropy_atomic_radius,range_atomic_radius,wtd_range_atomic_radius,std_atomic_radius,wtd_std_atomic_radius,mean_Density,wtd_mean_Density,gmean_Density,wtd_gmean_Density,entropy_Density,wtd_entropy_Density,range_Density,wtd_range_Density,std_Density,wtd_std_Density,mean_ElectronAffinity,wtd_mean_ElectronAffinity,gmean_ElectronAffinity,wtd_gmean_ElectronAffinity,entropy_ElectronAffinity,wtd_entropy_ElectronAffinity,range_ElectronAffinity,wtd_range_ElectronAffinity,std_ElectronAffinity,wtd_std_ElectronAffinity,mean_FusionHeat,wtd_mean_FusionHeat,gmean_FusionHeat,wtd_gmean_FusionHeat,entropy_FusionHeat,wtd_entropy_FusionHeat,range_FusionHeat,wtd_range_FusionHeat,std_FusionHeat,wtd_std_FusionHeat,mean_ThermalConductivity,wtd_mean_ThermalConductivity,gmean_ThermalConductivity,wtd_gmean_ThermalConductivity,entropy_ThermalConductivity,wtd_entropy_ThermalConductivity,range_ThermalConductivity,wtd_range_ThermalConductivity,std_ThermalConductivity,wtd_std_ThermalConductivity,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
number_of_elements,1.000000,NaN,NaN,NaN,NaN,0.939359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.972867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.971904,0.903625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.900813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.967576,NaN,NaN,NaN,NaN,NaN,NaN
mean_atomic_mass,NaN,1.000000,NaN,0.941275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_mean_atomic_mass,NaN,NaN,1.000000,NaN,0.965004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gmean_atomic_mass,NaN,0.941275,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_gmean_atomic_mass,NaN,NaN,0.965004,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entropy_atomic_mass,0.939359,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.964976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.972664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.931501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.928157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.963567,NaN,NaN,NaN,NaN,NaN,NaN
wtd_entropy_atomic_mass,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.962112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.918932,NaN,NaN,NaN,NaN,NaN
range_atomic_mass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.961199,0.917761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_range_atomic_mass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std_atomic_mass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.961199,NaN,1.000000,0.919023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_std_atomic_mass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.917761,NaN,0.919023,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.969378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_mean_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.992334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gmean_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.969378,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_gmean_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.992334,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entropy_fie,0.972867,NaN,NaN,NaN,NaN,0.964976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.997720,0.920008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.901815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.912723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.916744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.992695,0.907878,NaN,NaN,NaN,NaN,NaN
wtd_entropy_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
range_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.981582,0.940463,NaN,NaN,NaN,NaN,NaN,NaN,0.908540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_range_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.981582,NaN,1.000000,0.934482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_std_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.940463,NaN,0.934482,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.922654,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.915503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_mean_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.980084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gmean_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.915503,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_gmean_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.980084,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entropy_atomic_radius,0.971904,NaN,NaN,NaN,NaN,0.972664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.997720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.914092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.915502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.909561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.930474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.989497,NaN,NaN,NaN,NaN,NaN,NaN
wtd_entropy_atomic_radius,0.903625,NaN,NaN,NaN,NaN,NaN,0.962112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.920008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.914092,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.908157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.919032,0.951714,NaN,NaN,NaN,NaN,NaN
range_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.908540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.967533,0.957902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_range_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.967533,NaN,1.000000,0.944375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_std_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.922654,NaN,NaN,NaN,NaN,NaN,NaN,0.957902,NaN,0.944375,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_mean_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.942167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gmean_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.951506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_gmean_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.942167,0.951506,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entropy_Density,NaN,NaN,NaN,NaN,NaN,0.931501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.901815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.915502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.917324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.900092,NaN,NaN,NaN,NaN,NaN,NaN
wtd_entropy_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
range_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.960169,0.906473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_range_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.960169,NaN,1.000000,0.904274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_std_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.906473,NaN,0.904274,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_mean_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gmean_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_gmean_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entropy_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.912723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.909561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.904483,NaN,NaN,NaN,NaN,NaN,NaN
wtd_entropy_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
range_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.973394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_range_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.973394,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_std_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index(['number_of_elements', 'mean_atomic_mass', 'wtd_mean_atomic_mass',
       'gmean_atomic_mass', 'wtd_gmean_atomic_mass', 'entropy_atomic_mass',
       'wtd_entropy_atomic_mass', 'range_atomic_mass', 'wtd_range_atomic_mass',
       'std_atomic_mass', 'wtd_std_atomic_mass', 'mean_fie', 'wtd_mean_fie',
       'gmean_fie', 'wtd_gmean_fie', 'entropy_fie', 'wtd_entropy_fie',
       'range_fie', 'wtd_range_fie', 'std_fie', 'wtd_std_fie',
       'mean_atomic_radius', 'wtd_mean_atomic_radius', 'gmean_atomic_radius',
       'wtd_gmean_atomic_radius', 'entropy_atomic_radius',
       'wtd_entropy_atomic_radius', 'range_atomic_radius',
       'wtd_range_atomic_radius', 'std_atomic_radius', 'wtd_std_atomic_radius',
       'mean_Density', 'wtd_mean_Density', 'gmean_Density',
       'wtd_gmean_Density', 'entropy_Density', 'wtd_entropy_Density',
       'range_Density', 'wtd_range_Density', 'std_Density', 'wtd_std_Density',
       'mean_ElectronAffinity', 'wtd_mean_ElectronAffinity',
       'gmean_ElectronAffinity', 'wtd_gmean_ElectronAffinity',
       'entropy_ElectronAffinity', 'wtd_entropy_ElectronAffinity',
       'range_ElectronAffinity', 'wtd_range_ElectronAffinity',
       'std_ElectronAffinity', 'wtd_std_ElectronAffinity', 'mean_FusionHeat',
       'wtd_mean_FusionHeat', 'gmean_FusionHeat', 'wtd_gmean_FusionHeat',
       'entropy_FusionHeat', 'wtd_entropy_FusionHeat', 'range_FusionHeat',
       'wtd_range_FusionHeat', 'std_FusionHeat', 'wtd_std_FusionHeat',
       'mean_ThermalConductivity', 'wtd_mean_ThermalConductivity',
       'gmean_ThermalConductivity', 'wtd_gmean_ThermalConductivity',
       'entropy_ThermalConductivity', 'wtd_entropy_ThermalConductivity',
       'range_ThermalConductivity', 'wtd_range_ThermalConductivity',
       'std_ThermalConductivity', 'wtd_std_ThermalConductivity',
       'mean_Valence', 'wtd_mean_Valence', 'gmean_Valence',
       'wtd_gmean_Valence', 'entropy_Valence', 'wtd_entropy_Valence',
       'range_Valence', 'wtd_range_Valence', 'std_Valence', 'wtd_std_Valence',
       'critical_temp'],
      dtype='object')

In [ ]:
for column in df.columns:
    if "wtd" in column:
        print(column)

wtd_mean_atomic_mass
wtd_gmean_atomic_mass
wtd_entropy_atomic_mass
wtd_range_atomic_mass
wtd_std_atomic_mass
wtd_mean_fie
wtd_gmean_fie
wtd_entropy_fie
wtd_range_fie
wtd_std_fie
wtd_mean_atomic_radius
wtd_gmean_atomic_radius
wtd_entropy_atomic_radius
wtd_range_atomic_radius
wtd_std_atomic_radius
wtd_mean_Density
wtd_gmean_Density
wtd_entropy_Density
wtd_range_Density
wtd_std_Density
wtd_mean_ElectronAffinity
wtd_gmean_ElectronAffinity
wtd_entropy_ElectronAffinity
wtd_range_ElectronAffinity
wtd_std_ElectronAffinity
wtd_mean_FusionHeat
wtd_gmean_FusionHeat
wtd_entropy_FusionHeat
wtd_range_FusionHeat
wtd_std_FusionHeat
wtd_mean_ThermalConductivity
wtd_gmean_ThermalConductivity
wtd_entropy_ThermalConductivity
wtd_range_ThermalConductivity
wtd_std_ThermalConductivity
wtd_mean_Valence
wtd_gmean_Valence
wtd_entropy_Valence
wtd_range_Valence
wtd_std_Valence

In [ ]:
train_columns = list(df.columns)

# train_columns = [
#     "number_of_elements",
#     "wtd_mean_atomic_mass",
#     # "wtd_gmean_atomic_mass",
#     "wtd_entropy_atomic_mass",
#     "wtd_range_atomic_mass",
#     "wtd_std_atomic_mass",
#     "wtd_mean_fie",
#     # "wtd_gmean_fie",
#     # "wtd_entropy_fie",
#     "wtd_range_fie",
#     # "wtd_std_fie",
#     "wtd_mean_atomic_radius",
#     # "wtd_gmean_atomic_radius",
#     # "wtd_entropy_atomic_radius",
#     "wtd_range_atomic_radius",
#     "wtd_std_atomic_radius",
#     "wtd_mean_Density",
#     # "wtd_gmean_Density",
#     # "wtd_entropy_Density",
#     "wtd_range_Density",
#     "wtd_std_Density",
#     "wtd_mean_ElectronAffinity",
#     # "wtd_gmean_ElectronAffinity",
#     # "wtd_entropy_ElectronAffinity",
#     "wtd_range_ElectronAffinity",
#     "wtd_std_ElectronAffinity",
#     "wtd_mean_FusionHeat",
#     # "wtd_gmean_FusionHeat",
#     # "wtd_entropy_FusionHeat",
#     "wtd_range_FusionHeat",
#     "wtd_std_FusionHeat",
#     "wtd_mean_ThermalConductivity",
#     # "wtd_gmean_ThermalConductivity",
#     # "wtd_entropy_ThermalConductivity",
#     "wtd_range_ThermalConductivity",
#     "wtd_std_ThermalConductivity",
#     "wtd_mean_Valence",
#     # "wtd_gmean_Valence",
#     # "wtd_entropy_Valence",
#     "wtd_range_Valence",
#     "wtd_std_Valence",
#     "critical_temp",
# ]

# optimal_columns = [
#     "number_of_elements",
#     "wtd_mean_atomic_mass",
#     "wtd_mean_fie",
#     "wtd_mean_atomic_radius",
#     "wtd_mean_Density",
#     "wtd_mean_ElectronAffinity",
#     "wtd_mean_FusionHeat",
#     "wtd_mean_ThermalConductivity",
#     "wtd_mean_Valence",
#     "wtd_std_Valence",
#     "wtd_std_atomic_radius",
#     "critical_temp"
# ]

test_columns = train_columns.copy()
test_columns.remove("critical_temp")

df = df[train_columns].copy()

In [ ]:
corr_matrix = df.corr()
upper_triangle = np.triu(np.ones_like(corr_matrix, dtype=bool), k=1)

high_corr = corr_matrix.where(upper_triangle) > 0.9

num_high_corr_pairs = high_corr.sum().sum()

print(f"Число пар признаков с корреляцией > 0.9: {num_high_corr_pairs}")

Число пар признаков с корреляцией > 0.9: 73

In [ ]:
df.corr().where(lambda x: x > 0.9)

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,wtd_std_atomic_mass,mean_fie,wtd_mean_fie,gmean_fie,wtd_gmean_fie,entropy_fie,wtd_entropy_fie,range_fie,wtd_range_fie,std_fie,wtd_std_fie,mean_atomic_radius,wtd_mean_atomic_radius,gmean_atomic_radius,wtd_gmean_atomic_radius,entropy_atomic_radius,wtd_entropy_atomic_radius,range_atomic_radius,wtd_range_atomic_radius,std_atomic_radius,wtd_std_atomic_radius,mean_Density,wtd_mean_Density,gmean_Density,wtd_gmean_Density,entropy_Density,wtd_entropy_Density,range_Density,wtd_range_Density,std_Density,wtd_std_Density,mean_ElectronAffinity,wtd_mean_ElectronAffinity,gmean_ElectronAffinity,wtd_gmean_ElectronAffinity,entropy_ElectronAffinity,wtd_entropy_ElectronAffinity,range_ElectronAffinity,wtd_range_ElectronAffinity,std_ElectronAffinity,wtd_std_ElectronAffinity,mean_FusionHeat,wtd_mean_FusionHeat,gmean_FusionHeat,wtd_gmean_FusionHeat,entropy_FusionHeat,wtd_entropy_FusionHeat,range_FusionHeat,wtd_range_FusionHeat,std_FusionHeat,wtd_std_FusionHeat,mean_ThermalConductivity,wtd_mean_ThermalConductivity,gmean_ThermalConductivity,wtd_gmean_ThermalConductivity,entropy_ThermalConductivity,wtd_entropy_ThermalConductivity,range_ThermalConductivity,wtd_range_ThermalConductivity,std_ThermalConductivity,wtd_std_ThermalConductivity,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
number_of_elements,1.000000,NaN,NaN,NaN,NaN,0.939359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.972867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.971904,0.903625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.900813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.967576,NaN,NaN,NaN,NaN,NaN,NaN
mean_atomic_mass,NaN,1.000000,NaN,0.941275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_mean_atomic_mass,NaN,NaN,1.000000,NaN,0.965004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gmean_atomic_mass,NaN,0.941275,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_gmean_atomic_mass,NaN,NaN,0.965004,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entropy_atomic_mass,0.939359,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.964976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.972664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.931501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.928157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.963567,NaN,NaN,NaN,NaN,NaN,NaN
wtd_entropy_atomic_mass,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.962112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.918932,NaN,NaN,NaN,NaN,NaN
range_atomic_mass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.961199,0.917761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_range_atomic_mass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std_atomic_mass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.961199,NaN,1.000000,0.919023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_std_atomic_mass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.917761,NaN,0.919023,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.969378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_mean_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.992334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gmean_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.969378,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_gmean_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.992334,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entropy_fie,0.972867,NaN,NaN,NaN,NaN,0.964976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.997720,0.920008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.901815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.912723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.916744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.992695,0.907878,NaN,NaN,NaN,NaN,NaN
wtd_entropy_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
range_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.981582,0.940463,NaN,NaN,NaN,NaN,NaN,NaN,0.908540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_range_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.981582,NaN,1.000000,0.934482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_std_fie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.940463,NaN,0.934482,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.922654,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.915503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_mean_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.980084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gmean_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.915503,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_gmean_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.980084,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entropy_atomic_radius,0.971904,NaN,NaN,NaN,NaN,0.972664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.997720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.914092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.915502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.909561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.930474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.989497,NaN,NaN,NaN,NaN,NaN,NaN
wtd_entropy_atomic_radius,0.903625,NaN,NaN,NaN,NaN,NaN,0.962112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.920008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.914092,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.908157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.919032,0.951714,NaN,NaN,NaN,NaN,NaN
range_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.908540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.967533,0.957902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_range_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.967533,NaN,1.000000,0.944375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_std_atomic_radius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.922654,NaN,NaN,NaN,NaN,NaN,NaN,0.957902,NaN,0.944375,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_mean_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.942167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gmean_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.951506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_gmean_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.942167,0.951506,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entropy_Density,NaN,NaN,NaN,NaN,NaN,0.931501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.901815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.915502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.917324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.900092,NaN,NaN,NaN,NaN,NaN,NaN
wtd_entropy_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
range_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.960169,0.906473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_range_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.960169,NaN,1.000000,0.904274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_std_Density,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.906473,NaN,0.904274,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_mean_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gmean_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_gmean_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entropy_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.912723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.909561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.904483,NaN,NaN,NaN,NaN,NaN,NaN
wtd_entropy_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
range_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.973394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_range_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.973394,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wtd_std_ElectronAffinity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
X, y = df.iloc[:, :-1], df.iloc[:, -1]

# Baseline — решение

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=42, test_size=0.2, shuffle=True)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_valid)

print(f"{"R2":<4}:", model.score(X_valid, y_valid))
print(f"{"RMSE":<4}:", np.sqrt(mean_squared_error(y_valid, y_pred)))

R2  : 0.7263736035742483
RMSE: 17.644906836695498

In [ ]:
df_test = pd.read_csv("/content/test.csv")[test_columns]

X_test = df_test.iloc[:, :]

y_pred = model.predict(X_test)

results = pd.DataFrame({
    "index": range(len(y_pred)),
    "critical_temp": y_pred
})

results.to_csv("sumbission_normal.csv", index=False)

In [ ]:
y_log_train = np.log1p(y_train)
y_log_valid = np.log1p(y_valid)

model = LinearRegression()
model.fit(X_train, y_log_train)
y_log_pred = model.predict(X_valid)

y_pred_original = np.expm1(y_log_pred)
y_valid_original = np.expm1(y_log_valid)

r2_real = r2_score(y_valid_original, y_pred_original)
rmse_real = np.sqrt(mean_squared_error(y_valid_original, y_pred_original))

print(f"{'R2':<4}: {r2_real:.4f}")
print(f"{'RMSE':<4}: {rmse_real:.4f}")

R2  : 0.7293
RMSE: 17.5510

In [ ]:
df_test = pd.read_csv("/content/test.csv")[test_columns]

X_test = df_test.iloc[:, :]

y_pred = model.predict(X_test)

results = pd.DataFrame({
    "index": range(len(y_pred)),
    "critical_temp": np.expm1(y_pred)
})

results.to_csv("sumbission_normal_log.csv", index=False)

# Создание моделей

Большое число скоррелированных признаков подсказывает попробовать воспользоваться регуляризацией. Попробуем как L2, так и L1

In [ ]:
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", RidgeCV(
        alphas=np.logspace(-3, 1, 100),
        cv=5,
        scoring="neg_mean_squared_error"
    ))
])

pipe.fit(X_train, y_train)

best_alpha = pipe.named_steps["model"].alpha_

y_pred = pipe.predict(X_valid)

r2_real = r2_score(y_valid, y_pred)
rmse_real = np.sqrt(mean_squared_error(y_valid, y_pred))

print("Best alpha:", best_alpha)
print(f"{'R2':<4}: {r2_real:.4f}")
print(f"{'RMSE':<4}: {rmse_real:.4f}")

Best alpha: 0.05462277217684343
R2  : 0.7264
RMSE: 17.6447

In [ ]:
df_test = pd.read_csv("/content/test.csv")[test_columns]

X_test = df_test.iloc[:, :]

y_pred = pipe.predict(X_test)

results = pd.DataFrame({
    "index": range(len(y_pred)),
    "critical_temp": y_pred
})

results.to_csv("submission_ridge.csv", index=False)

In [ ]:
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", RidgeCV(
        alphas=np.logspace(-3, 1, 100),
        cv=5,
        scoring="neg_mean_squared_error"
    ))
])

y_log_train = np.log1p(y_train)
y_log_valid = np.log1p(y_valid)

pipe.fit(X_train, y_log_train)

best_alpha = pipe.named_steps["model"].alpha_

y_log_pred = pipe.predict(X_valid)

y_pred_original = np.expm1(y_log_pred)
y_valid_original = np.expm1(y_log_valid)

r2_real = r2_score(y_valid_original, y_pred_original)
rmse_real = np.sqrt(mean_squared_error(y_valid_original, y_pred_original))

print("Best alpha:", best_alpha)
print(f"{'R2':<4}: {r2_real:.4f}")
print(f"{'RMSE':<4}: {rmse_real:.4f}")

Best alpha: 0.10476157527896651
R2  : 0.7295
RMSE: 17.5451

In [ ]:
df_test = pd.read_csv("/content/test.csv")[test_columns]

X_test = df_test.iloc[:, :]

y_pred = pipe.predict(X_test)

results = pd.DataFrame({
    "index": range(len(y_pred)),
    "critical_temp": np.expm1(y_pred)
})

results.to_csv("submission_ridge_log.csv", index=False)

In [ ]:
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LassoCV(
        alphas=np.logspace(-5, -4, 100),
        # alphas=[2.1544346900318823e-05],
        cv=5,
        max_iter=30_000,
        tol=1e-4,
        random_state=42
    ))
])

pipe.fit(X_train, y_train)

best_alpha = pipe.named_steps["model"].alpha_
y_pred = pipe.predict(X_valid)

r2 = r2_score(y_valid, y_pred)
rmse = np.sqrt(mean_squared_error(y_valid, y_pred))

print("Best alpha:", best_alpha)
print(f"{'R2':<4}: {r2:.4f}")
print(f"{'RMSE':<4}: {rmse:.4f}")

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 536118.1002090359, tolerance: 1288.4169540315613
  model = cd_fast.enet_coordinate_descent_gram(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 719818.1356532942, tolerance: 1296.9637487269472
  model = cd_fast.enet_coordinate_descent_gram(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 12266.279038819019, tolerance: 1296.9637487269472
  model = cd_fast.enet_coordinate_descent_gram(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 636110.3389211013, tolerance: 1294.9444324450803
  model = cd_fast.enet_coordinate_descent_gram(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 8724.028733297717, tolerance: 1294.9444324450803
  model = cd_fast.enet_coordinate_descent_gram(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 465315.0018053327, tolerance: 1298.369393813424
  model = cd_fast.enet_coordinate_descent_gram(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1680.7454025275074, tolerance: 1298.369393813424
  model = cd_fast.enet_coordinate_descent_gram(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 690025.4228572135, tolerance: 1291.6734772439477
  model = cd_fast.enet_coordinate_descent_gram(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 7938.791698822752, tolerance: 1291.6734772439477
  model = cd_fast.enet_coordinate_descent_gram(

Best alpha: 0.0001
R2  : 0.7263
RMSE: 17.6471

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.997e+05, tolerance: 1.618e+03
  model = cd_fast.enet_coordinate_descent(

In [ ]:
df_test = pd.read_csv("/content/test.csv")[test_columns]

X_test = df_test.iloc[:, :]

y_pred = pipe.predict(X_test)

results = pd.DataFrame({
    "index": range(len(y_pred)),
    "critical_temp": y_pred
})

results.to_csv("submission_lasso.csv", index=False)

In [ ]:
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LassoCV(
        alphas=np.logspace(-5, -3, 100),
        cv=5,
        max_iter=30_000,
        random_state=42
    ))
])

y_log_train = np.log1p(y_train)
y_log_valid = np.log1p(y_valid)

pipe.fit(X_train, y_log_train)

best_alpha = pipe.named_steps["model"].alpha_

y_log_pred = pipe.predict(X_valid)

y_pred_original = np.expm1(y_log_pred)
y_valid_original = np.expm1(y_log_valid)

r2_real = r2_score(y_valid_original, y_pred_original)
rmse_real = np.sqrt(mean_squared_error(y_valid_original, y_pred_original))

print("Best alpha:", best_alpha)
print(f"{'R2':<4}: {r2_real:.4f}")
print(f"{'RMSE':<4}: {rmse_real:.4f}")

Best alpha: 2.0092330025650458e-05
R2  : 0.7295
RMSE: 17.5432

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.977e+02, tolerance: 2.267e+00
  model = cd_fast.enet_coordinate_descent(

In [ ]:
df_test = pd.read_csv("/content/test.csv")[test_columns]

X_test = df_test.iloc[:, :]

y_pred = pipe.predict(X_test)

results = pd.DataFrame({
    "index": range(len(y_pred)),
    "critical_temp": np.expm1(y_pred)
})

results.to_csv("submission_lasso_log.csv", index=False)